config/routes.rb
Rails.application.routes.draw do
  
  get 'expences/edit'
  get 'approval/index'
  get 'approvals/index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  
  get 'timecards/index'
  get 'timecards/:id', to: 'timecards#show'
  get 'timecards/:id/edit', to: 'timecards#edit'
  patch 'timecards', to: 'timecards#update'
  
  get 'approval', to: 'approval#index'
  get 'approval/(:target)', to: 'approval#index'
  patch 'approval(:id)', to: 'approval#update'
  
  resources :expences
  
  get 'static_pages/about',as: 'about'
  get 'static_pages/help',as: 'help'
  get 'static_pages/home',as: 'home'
  
  get 'tcmente', to: 'timecard_master_mente#index'
  post 'tcmente', to: 'timecard_master_mente#create'
  post 'tcmente/(:target_month)', to: 'timecard_master_mente#create_cal'
  
  root :to => 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.find_by(id: session[:user_id])
  end
  
  def about
    # render plain: "test"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="center jumbotron">
  <h1>aboutpage</h1>
  
</div>

app/views/static_pages/help.html.erb
<p>help page</p>

app/views/static_pages/home.html.erb
<h2 align="center">職員Menu</h2>
<table width="80%" align="center">
    <tbody>
        <tr>
            <td width="50%" height="50" style="text-align: center">
            	<%= link_to "タイムカード", timecards_index_path, class: 'btn btn-primary', style: "width:80%; height:40px"%>
        	</td>
            <td width="50%" height="50" style="text-align: center">
            	<%= link_to "経費", expences_path, class: 'btn btn-primary', style: "width:80%; height:40px"%>
			</td>
        </tr>
        <tr>
            <td  width="50%" height="50" style="text-align: center">
            	<%#= button_tag "給与明細", class: "btn btn-primary", style: "width:80%; height:40px" %>
						</td>
            <td  width="50%" height="50" style="text-align: center"></td>
        </tr>
        <tr>
            <td  width="50%" height="50"></td>
            <td  width="50%" height="50"></td>
        </tr>
    </tbody>
</table>

<% if @user.admin %>
	<h2 align="center">管理者Menu</h2>
	<table width="80%"  align="center">
		<tr>
			<td width="50%" height="50" style="text-align: center">
		    	<%= link_to "社員マスタ", users_path, class: "btn btn-primary", style: "width:80%; height:40px" %>
		    </td>
		    <td width="50%" height="50" style="text-align: center">
		    	<%= link_to "TC・経費承認", approval_path, class: "btn btn-primary", style: "width:80%; height:40px" %>
			</td>
		</tr>
	    <tr>
	    	<td width="50%" height="50" style="text-align: center">
	    		<%= link_to "TCマスタメンテ", tcmente_path, class: "btn btn-primary", style: "width:80%; height:40px" %>
	    	</th>
	        <td width="50%" height="50"></td>
	    </tr>
	</table>
<% end %>