config/routes.rb
Rails.application.routes.draw do
  
  get 'expences/edit'
  get 'approval/index'
  get 'approvals/index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  
  get 'timecards/index'
  get 'timecards/:id', to: 'timecards#show'
  get 'timecards/:id/edit', to: 'timecards#edit'
  patch 'timecards', to: 'timecards#update'
  
  get 'approval', to: 'approval#index'
  get 'approval/(:target)', to: 'approval#index'
  patch 'approval(:id)', to: 'approval#update'
  
  resources :expences
  
  get 'static_pages/about',as: 'about'
  get 'static_pages/help',as: 'help'
  get 'static_pages/home',as: 'home'
  
  get 'tcmente', to: 'timecard_master_mente#index'
  post 'tcmente', to: 'timecard_master_mente#create'
  post 'tcmente/(:target_month)', to: 'timecard_master_mente#create_cal'
  
  root :to => 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/approval_controller.rb
class ApprovalController < ApplicationController
  def index
    @tc_index = TimecardIndece.all
    @users = User.all
    @target = params[:target]
    if @target.nil?
      @target = TimecardIndece.last.target_month
    end
  end
  
  def update
    tc = Timecard.find(params[:id])
    
    if params[:type] == "tc"
      tc.shinsei_kbn = 2
    else
      tc.keihi_shinsei_kbn = 2
    end
    
    if tc.save
      flash[:success] = "承認を行いました。"
    else
      flash[:error] = "承認に失敗しました"
    end
    redirect_to approval_path
  end
end

app/helpers/approval_helper.rb
module ApprovalHelper
end

app/views/approval/_approval_sub.html.erb
<% tc = Timecard.find_by(user_id: u.id,target_month: @target) %>
<tr>
	<td>
		<%= u.name %>
	</td>
	
	<!-- -----Timecard------- -->
	<td style="text-align: center">
		<% if !tc.nil? %>
			<%= Generic.find_by(kbn: "K01", key1: tc.shinsei_kbn).data1 %>
		<% else %>
			未作成
		<% end %>
	</td>
	<td>
		<% if !tc.nil? %>
			<%= link_to "確認", "#{timecards_path}/#{tc.id}"  %>
		<% end %>
		<% if !tc.nil? && tc.shinsei_kbn == 1 %>
			<%= link_to "承認", approval_path(id: tc.id, type: "exp"),method: :patch,data: {confirm: "承認して宜しいですか？"} %>
		<% end %>
	</td>
	
	<!-- -----expences------- -->
	<td style="text-align: center">
		<% if !tc.nil? %>
			<%= Generic.find_by(kbn: "K01", key1: tc.keihi_shinsei_kbn).data1 %>
		<% else %>
			未作成
		<% end %>
	</td>
	<td>
		<% if !tc.nil? %>
			<%= link_to "確認", expence_path(id: tc.id)  %>
		<% end %>
		<% if !tc.nil? && tc.keihi_shinsei_kbn == 1 %>
			<%= link_to "承認", approval_path(id:tc.id,type:"exp"),method: :patch,data: {confirm: "承認して宜しいですか？"} %>
		<% end %>
	</td>
</tr>

app/views/approval/index.html.erb
<% provide(:title, '承認画面') %>
<br />
<div class="container" width="80%">
	<h3>TC1・経費承認</h3>	
	対象年月：
	<%= select :approval, :tcindex, 
				options_for_select(@tc_index.pluck(:target_month),selected: @target),{}, onchange: "test('#{approval_path}')" %>
</div>
<br />

<div class="container">
	<table class="my_table">
		<thead>
			<tr>
				<th width="30%" rowspan=2>名前</th>
				<th width="35%" colspan=2>TC</th>
				<th width="35%" colspan=2>経費</th>
			</tr>
			<tr>
				<th>状況</th>
				<th>アクション</th>
				<th>状況</th>
				<th>アクション</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |u| %>
				<%= render 'approval_sub', u: u %>
			<% end %>
		</tbody>
	</table>
	
	<div class="row">
		<div class="col-md-2 offset-md-10">
			<%= link_to "戻る", home_path, class:"btn btn-primary" %>
		</div>
	</div>
</div>