config/routes.rb
Rails.application.routes.draw do
  
  get 'expences/edit'
  get 'approval/index'
  get 'approvals/index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  
  get 'timecards/index'
  get 'timecards/:id', to: 'timecards#show'
  get 'timecards/:id/edit', to: 'timecards#edit'
  patch 'timecards', to: 'timecards#update'
  
  get 'approval', to: 'approval#index'
  get 'approval/(:target)', to: 'approval#index'
  patch 'approval(:id)', to: 'approval#update'
  
  resources :expences
  
  get 'static_pages/about',as: 'about'
  get 'static_pages/help',as: 'help'
  get 'static_pages/home',as: 'home'
  
  get 'tcmente', to: 'timecard_master_mente#index'
  post 'tcmente', to: 'timecard_master_mente#create'
  post 'tcmente/(:target_month)', to: 'timecard_master_mente#create_cal'
  
  root :to => 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
    @edit_user = User.find_by(id: session[:user_id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params) 
    
    if @user.save
      @user.save
      flash[:success] = "新規アカウントを作成しました"
      redirect_to users_path
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find_by(params.require(:user).permit(:id))
    
    if @user.update_columns(name: params[:user][:name], email: params[:user][:email])
      flash[:success] = "社員情報を更新しました"
      render 'edit'
    else
      render 'edit'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<div class="col-md-6 col-md-offset-3">	
		<%= form_for(@user, url: user_path(@user), method: :put) do |f| %>
			<%= render 'shared/error_messages' %>
			
			<%= f.hidden_field :id, value: @user.id %>
			
			<%= f.label "名前" %>
			<%= f.text_field :name ,class: 'form-control' %>
			
			<br />
			<%= f.label "メールアドレス" %>
			<%= f.text_field :email ,class: 'form-control' %>
			
			<br />
			<%= link_to "戻る" ,users_path, class: "btn btn-primary" %>
			<%= f.submit "更新" , class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "社員一覧") %>
<br />
<div class="container" style="width:80%">
	<table class="my_table">
		<thead>
			<tr>
				<th width="50%">名前</td>
				<th width="20%">役職</td>
				<th width="30%">アクション</td>
			</tr>
		</thead>
		<tbody>
			<% User.all.each do |user| %>
				<tr>
					<td>
					  <%= user.name %>
					</td>
					<td>
					  <%= user.admin ? "所属長" :"一般" %>
					</td>
					<td>
						<%= link_to "参照", user_path(user)  %>&nbsp;&nbsp;
						<%= link_to "編集", edit_user_path(user) %>&nbsp;&nbsp;
						<%= link_to "削除", "#" %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	
	<div class="row">
		<div class="col-md-2 offset-md-8">
			<%= link_to "戻る", home_path, class:"btn btn-primary" %>
		</div>
		<div class="col-md-2">
			<%= link_to "新規登録" , new_user_path, action: :patch ,class: "btn btn-primary" %>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, '社員登録') %>

<h1>新規社員登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label "名前" %>
      <%= f.text_field :name , class: 'form-control'%>

      <%= f.label "メールアドレス" %>
	  	<%= f.email_field :email, class: 'form-control' %>
	  
      <%= f.label "パスワード" %>
	  	<%= f.password_field :password, class: 'form-control' %>	
		
      <%= f.label "パスワード(確認用)" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
			<br />
			
      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<table border=1 width="50%" align="center">
	<tr>
		<td bgcolor="gray">
			名前
		</td>
		<td>
			<%= @user.name %>
		</td>
	</tr>
	<tr>
		<td bgcolor="gray">
			email
		</td>
		<td>
			<%= @user.email %>
		</td>
	</tr>
	<tr>
		<td bgcolor="gray">
			役職
		</td>
		<td>
			<%= @user.admin ? "所属長" : "一般" %>
		</td>
	</tr>
</table>