config/routes.rb
Rails.application.routes.draw do
  
  get 'expences/edit'
  get 'approval/index'
  get 'approvals/index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  
  get 'timecards/index'
  get 'timecards/:id', to: 'timecards#show'
  get 'timecards/:id/edit', to: 'timecards#edit'
  patch 'timecards', to: 'timecards#update'
  
  get 'approval', to: 'approval#index'
  get 'approval/(:target)', to: 'approval#index'
  patch 'approval(:id)', to: 'approval#update'
  
  resources :expences
  
  get 'static_pages/about',as: 'about'
  get 'static_pages/help',as: 'help'
  get 'static_pages/home',as: 'home'
  
  get 'tcmente', to: 'timecard_master_mente#index'
  post 'tcmente', to: 'timecard_master_mente#create'
  post 'tcmente/(:target_month)', to: 'timecard_master_mente#create_cal'
  
  root :to => 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<script>
  $('.dropdown-toggle').dropdown()
</script>

<!-- <header class="navbar navbar-fixed-top navbar-inverse"> -->
<header>
  <nav class="navbar navbar-dark bg-dark">
	  <%= link_to "社内システム", root_path, class:"navbar-brand" %>
	    
    <% if logged_in? %>
    	<div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          アカウント
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        	<%= link_to "社員情報", current_user,class:"dropdown-item" %>
        	<div class="dropdown-divider"></div>
          <%= link_to "ログアウト", logout_path, method: :delete,class:"dropdown-item" %>
        </div>
      </div>
    <% end %>
	</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
        <%= csrf_meta_tags %>
	    <%= stylesheet_link_tag    'application', media: 'all',
	                               'data-turbolinks-track': 'reload' %>
	    <%= javascript_include_tag 'application',
	                               'data-turbolinks-track': 'reload' %>
	    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
   	  <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>